# Generated by Django 4.0.3 on 2022-04-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updation time')),
            ],
        ),
    ]
